### ISSUE TITLE
new tab for livinglibrary

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/donordb#3]
- same domain but use /livinglibrary
- new page rather in frame of app
- same folder/server. diff port route. node rather than php
- make title field optional
- hide dollar amount for donor, if possible hide for everyone except business officer otherwise we can send an annual report with dollars amount

**Comment by scottsalvaggio** [comment]
Added as part of [v2.0.0 release](https://github.com/dulibrarytech/donordb/releases/tag/v2.0.0)
